from __future__ import annotations

import re
import sys
from pathlib import Path


SCRIPT = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).parents[1] / "梦想小镇日常一体化.user.js"
text = SCRIPT.read_text(encoding="utf-8")


def require(name: str, condition: bool) -> None:
    if not condition:
        raise AssertionError(name)
    print(f"PASS: {name}")


require("v3.38 metadata and shared panel version", "// @version      3.38" in text and "const SCRIPT_VERSION = '3.38';" in text and "v${SCRIPT_VERSION}" in text)
require("panel registers at document start", "// @run-at       document-start" in text)
require("panel reveals only after scheduler is forced open", "panel.style.visibility = 'hidden';" in text and text.count("schedWrap.open = true;") >= 2 and "panel.style.visibility = 'visible';" in text and "requestAnimationFrame(() =>" in text)
require("panel has no stale hardcoded title", "梦想小镇日常 v3.18" not in text and "梦想小镇日常 v3.20" not in text)
require("panel doubles desktop width", "width:560px" in text and "box-sizing:border-box" in text)
require("panel control rows use two columns", "#dxzxx-rows,#dxzxx-project-rows{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))" in text)
require("panel configuration area uses two columns", 'class="panel-columns"' in text and 'class="panel-column"' in text)
require("panel details default open", text.count("<details open") >= 5)
require("panel action buttons use two columns", 'class="panel-actions"' in text and "grid-template-columns:repeat(2,minmax(0,1fr));gap:0 6px" in text)
require("panel scheduler information uses freed space", "#dxzxx-sched-status{max-height:110px" in text)
require("panel falls back to one column on narrow screens", "@media (max-width:620px)" in text and "grid-template-columns:1fr" in text)
require("panel enlarges font while overriding site line height", "font-size:12px;line-height:1.25;width:560px" in text and "font-size:12px;line-height:1.2;" in text)
require("panel scheduler inner box overrides site line height", "#dxzxx-sched-wrap>div{line-height:1.25;}" in text)
top_start = text.index('class="panel-columns"')
daily_ui = text.index("每日项目（早饭后执行）", top_start)
module_ui = text.index("自动驾驶功能开关（按${AutoPilot.PLAN.length}步顺序）", daily_ui)
require("panel orders common controls daily projects then module switches", top_start < daily_ui < module_ui)
require("panel merges duplicate autopilot preview into switches", "自动驾驶流程（${AutoPilot.PLAN.length} 步）" not in text and "dxzxx-plan-list" not in text)
require("panel module switches follow actual autopilot order", "const planOrder = new Map(AutoPilot.PLAN.map" in text and ".sort((a, b) => (planOrder.get(a.id) ?? 999)" in text)
require("merged module switches highlight current autopilot module", "row.dataset.module = m.id;" in text and "row.classList.toggle('current', row.dataset.module === currentModule)" in text)
require("recipe target redundant label removed", '<div class="label">目标等级</div>' not in text)
require("every visible module switch has single run button", 'class="single-run" data-run-module="${m.id}"' in text and "panel.querySelectorAll('[data-run-module]')" in text)
require("single run follows real autopilot route", "startSingle(moduleId)" in text and "const stepIndex = this.PLAN.findIndex" in text and "setTimeout(() => this.continue(), 300);" in text)
require("single run bypasses persistent module switch", "if (!state.singleModule && !isEnabled(step.module))" in text)
require("single run stops after one module", "if (state.singleModule)" in text and "✓ 单项运行完成" in text and "this.stop(`${state.singleModule} 单项完成`);" in text)
require("single run restores only previous scheduler state", "resumeSchedulerAfterSingle: schedulerWasOn" in text and "previousState.singleModule ? !!previousState.resumeSchedulerAfterSingle : true" in text)
require("server time accepts current and legacy labels", "/(?:驯鹿|家园)报时[：:]/" in text)
require("server clock advances from static page sample", "_serverClockCapturedAt" in text and "localNow - this._serverClockCapturedAt" in text)

coupon_ids = re.search(r"PROP_IDS:\s*\[([^\]]+)\]", text)
require("food coupon whitelist exists", coupon_ids is not None)
ids = [int(value) for value in re.findall(r"\d+", coupon_ids.group(1))]
require("food coupon uses only legacy 8 ids", ids == [244, 21, 22, 23, 24, 25, 245, 224])
require("food coupon matches real warehouse", "p === '/xz/warehouse'" in text)
require("food coupon matches current exchange path", "(?:prop_)?food_random_" in text)
require("food coupon reads remaining quantity", "const remaining = quantityMatch ? parseInt(quantityMatch[1], 10) : null;" in text)
require("food coupon returns only after zero", "if (remaining === 0)" in text and "已归零，回仓库" in text)
require("food coupon uses exchange while nonzero", "if (exchangeBtn && remaining !== 0)" in text)
require("food coupon has no text fallback", "名字含\"食材\"/\"调料\"/\"随机\"" not in text)
daily_start = text.index("const DAILY_SCHEDULE = [")
daily_end = text.index("const DYNAMIC_SCHEDULE = [")
daily = text[daily_start:daily_end]
require("food coupon is in daily scheduler", "id: 'foodCoupon', module: 'foodCoupon'" in daily)

require("bag matches current result URL", r"/\/xz\/(?:prop|open)_bag_/" in text)
require("bag clicks only first item", "Utils.click(links[0]);" in text)
require("bag no longer clickAll", "Utils.clickAll(links, '礼包')" not in text)
require("bag completes only when empty", "礼包: 无可用" in text and "return true;" in text)

require("autopilot removed same-page advance", "session.lastPage" not in text and "5s 内重复" not in text)
require("autopilot clears emergency stop on start", "Utils.gset('autopilot_emergency_stop', false);" in text)
require("autopilot continues disabled steps on home", "setTimeout(() => this.continue(), 700);" in text)
require("autopilot requires explicit completion", "if (completed === true)" in text)
require("router yields plan modules", "由 AutoPilot 独占，Router 不重复执行" in text)
require("router does not mark action-in-progress complete", "仍有后续动作，不写完成标志" in text)
require("autopilot food coupon route is real", "{ module: 'foodCoupon', navSteps: [{ text: '仓库'," in text)
require("autopilot includes market purchase", "{ module: 'market',     navSteps: [{ text: '菜场'," in text)
require("autopilot includes daily NPC visits", "{ module: 'dailyNpc',   navSteps: [{ text: '菜场'," in text)
require("autopilot includes daily friend projects", "{ module: 'dailyFriend', navSteps: [{ text: '好友'," in text)
require("autopilot includes daily bar projects", "{ module: 'dailyBar',   navSteps: [{ text: '广场'," in text)
require("autopilot includes extra wish project", "{ module: 'extraWish',  navSteps: [{ text: '许愿'," in text)
require("autopilot includes vitality claims", "{ module: 'vitality',   navSteps: [{ text: '今日活跃'," in text)
require("merged autopilot switches use live plan length", "自动驾驶功能开关（按${AutoPilot.PLAN.length}步顺序）" in text)
require("autopilot recipe route is dynamic", "{ text: '可升级'," in text and "hrefPattern: '^/xz/cookbook_\\\\d+_3_1$'" in text)
require("autopilot is labelled one-shot", "🚀 立即跑一轮全套" in text and "🚀 自动跑全套日常" not in text)

require("guardian continues one shot per page", "guardianLaunch') && oc.includes('82') && oc.includes(',1)'" in text)
require("guardian replenishes 300", "input.value = '300';" in text and "buyByActivity(0,82,0)" in text)
require("egg action returns in-progress", "扭蛋: 已扭" in text and "return false;" in text)
require("daily projects exclude moving", "DAILY_PROJECT_DEFS" in text and "project_move" not in text)
require("daily project labels show vitality recommendations", "打蟑螂（推荐15次）" in text and "翻橱柜（推荐20次）" in text and "点赞/被赞（推荐5次）" in text)
require("daily project counts persist on input and change", "addEventListener('input', saveProjectCount)" in text and "addEventListener('change', saveProjectCount)" in text)
require("daily projects use 6am game day", "date.getTime() - 6 * 3600000" in text)
require("daily friend actions are configurable", "['like', 'dig', 'roach'].some" in text and "DailyProjectState.remaining(type, state)" in text)
require("daily bar actions are configurable", "DailyProjectState.remaining('fist'" in text and "DailyProjectState.remaining('cup'" in text and "DailyProjectState.remaining('number'" in text)
require("daily NPC project is one complete round", "拜访NPC（推荐1轮）" in text and "['garden', 'wenjie'].every" in text and "本轮完成 1/1" in text)
require("daily NPC round includes both visits", "visitHere('garden', '菜园姐')" in text and "visitHere('wenjie', '雯姐')" in text)
require("daily NPC migrates v3.33 partial count", "v334_npc_round_migrated" in text and "state.counts.npc = complete ? 1 : 0;" in text)
require("daily NPC target is capped to one round", "id === 'npc' ? 1 : 500" in text)
require("daily NPC input is capped to one round", "max=\"${p.id === 'npc' ? 1 : 500}\"" in text)
require("daily NPC is independent from paid market", "module: 'dailyNpc'" in text and "['dailyFriend', 'dailyBar', 'dailyNpc', 'extraWish']" in text)
require("friend list prioritizes roach markers", "img[src=\"/readImg/xz_cockroach\"]" in text and "const marked = links.filter(hasRoachMark);" in text)
require("friend floors follow roach markers", "const markedRoachFloor = floorLinks.find" in text and "Utils.click(floorToVisit);" in text)
require("autopilot hands off to scheduler", "自动驾驶: 已交接长期循环调度器" in text and "Scheduler.start();" in text)
require("emergency stop does not restart scheduler", "Esc 紧急停止', { resumeScheduler: false }" in text and "面板停止', { resumeScheduler: false }" in text)
require("vitality claims first available award", "a[onclick^='addVitalityAward']" in text and "今日活跃: 领取第一项" in text)
require("morning and evening reward sweeps exist", "vitalityMorning" in daily and "vitalityEvening" in daily and "seasonMorning" in daily and "seasonEvening" in daily and "eggMorning" in daily and "eggEvening" in daily)
require("temporary reward routes are optional", "optional: true" in daily and "可选入口" in text)
require("scheduled modules are isolated", "与当前调度阶段" in text and "mod.requiresScheduled" in text)

require("market discount is exactly 666", "DISCOUNT_PRICE: 666" in text and "price === this.CONFIG.DISCOUNT_PRICE" in text)
require("market discount dedupes by server hour", "market_last_discount_hour" in text)
require("market parses current daily market rows", "a[onclick^='buyDayFood']" in text and r"buyDayFood\((\d+),(\d+),(\d+)\)" in text)
require("market keeps old staple thresholds", "LEVEL1_TARGET: 950" in text and "LEVEL1_MAX_PRICE: 519" in text and "LEVEL2_TARGET: 950" in text and "LEVEL2_MAX_PRICE: 2650" in text and "FORCE_BUY_2: ['鸡肉', '猪肉']" in text)
require("market claims Tuesday reserve coupon first", "a[onclick^='getEverydayReserve']" in text and "已领取周二日常食材预定券" in text)
require("market claim remains in progress across refresh", "Utils.click(reserveClaim);" in text and "return false;" in text)
market_run = text[text.index("MOD.market = {"):text.index("// ----- 7. 食材券")]
require("market explicitly completes when no purchase remains", "市场: 无常驻菜" in market_run and "市场: 常驻菜全部达标" in market_run and market_run.count("return true;") >= 5)
require("market purchase remains in progress across refresh", "Utils.click(foodToBuy.buyButton);" in market_run and "return false;" in market_run)
require("router respects explicit in-progress result", "(!inPlan && completed !== false)" in text)
require("facility threshold restored to 5", "MIN_COUNT: 5" in text)
require("facility schedule capped at 24h", "Math.min(remainingMs + offsetMs, 24 * 3600000)" in text)
require("restaurant oil has independent switch", "restaurant_oil: true" in text and "restaurant_oil', true" in text)
require("restaurant oil threshold restored", "if (cur < 11000)" in text)
require("restaurant roach has failure stop and hard cap", "MAX_ROACH_ATTEMPTS: 20" in text and "restaurant_roach_attempts" in text and "打蟑螂已停止" in text)
require("restaurant floor detection cannot oscillate between siblings", "el.previousElementSibling || el.nextElementSibling" not in text and ".some(tryMatch);" in text)
require("scheduler expires persisted phases before module execution", "recoverExpiredPhase(path)" in text and text.index("recoverExpiredPhase(path)") < text.index("const activePhase = Scheduler.isOn()"))
require("expired restaurant phase disables roach action", "超时自救已关闭打蟑螂" in text and "Utils.gset('restaurant_remaining_floors', []);" in text)
require("restaurant master switch is clearly labelled", "餐厅管理（总开关）" in text)
restaurant_start = text.index("MOD.restaurant = {")
restaurant_end = text.index("// ----- 10.", restaurant_start)
restaurant_run = text[restaurant_start:restaurant_end]
restaurant_ui_start = text.index("<summary>餐厅子开关</summary>")
restaurant_ui_end = text.index("<summary>食谱升级配置</summary>", restaurant_ui_start)
restaurant_ui = text[restaurant_ui_start:restaurant_ui_end]
require("own restaurant direct roach action runs before floor scan", "async killCurrentRoach()" in restaurant_run and "a[onclick^='killCockroach']" in restaurant_run and restaurant_run.index("killCurrentRoach())") < restaurant_run.index("detectInfectedFloors()"))
require("own restaurant dig UI and runtime are removed", "自动翻橱柜" not in restaurant_ui and "digOne" not in restaurant_run and "MAX_DIG_ATTEMPTS" not in restaurant_run)
require("v337 clears stale restaurant dig settings", "v337_restaurant_dig_removed" in text and "Utils.gset('restaurant_dig', false);" in text)
require("restaurant mailbox switch defaults on", "restaurant_mailbox: true" in text and "餐厅后领取系统邮件" in text)
require("mailbox scans only system first page", "p === '/xz/mailbox' || p === '/xz/mailbox_0_1'" in text and "mailbox_0_2" not in text)
require("mailbox claim is exact and attachment-only", "text === '领取'" in text and r"/^getMailProp\(\d+,\s*0\);?$/" in text)
require("mailbox claims one gift per refresh", "Utils.click(claim);" in text and "领取第一份系统礼物，刷新后继续检查" in text and "return false;" in text)
require("mailbox completes only when no claim remains", "系统首页没有可领取礼物" in text and "系统礼物已检查" in text)
require("recipe default is off", text.count("recipe_target_level', 'off'") >= 2)
require("recipe uses middle-tier name in UI", '<option value="中品">升级到中品</option>' in text and "升级到中品（原特色）" not in text)
require("recipe keeps legacy middle-tier parser alias", "'中品': 1, '特色': 1" in text)
require("recipe migrates legacy target", "recipe_target_level', 'off') === '特色'" in text and "recipe_target_level', '中品'" in text)
require("recipe parses plain-text detail level", "食谱等级[:：]\\s*(金牌(?:\\d+级)?|极品|上品|中品|特色|普通)" in text)
detail_start = text.index("async processDetail()")
detail_end = text.index("// 找普通升级按钮", detail_start)
detail = text[detail_start:detail_end]
require("recipe checks target before upgrade button", "currentLevel >= targetLevel" in detail and detail.index("currentLevel >= targetLevel") < detail.index("findNormalUpgradeButton"))
require("recipe fails closed when level is unknown", "currentLevel === undefined || targetLevel === undefined" in detail and "等级解析失败，已跳过" in detail)
require("recipe scan skips blocked items", "scanStateKey: 'recipe_scan_state'" in text and "blocked.includes(link.getAttribute('href') || '')" in text)
require("recipe continues after insufficient materials", "材料或条件不足" in text and "继续扫描其它菜品" in text)
cookbook_start = text.index("async processCookbook()")
cookbook_end = text.index("// 找可升级项", cookbook_start)
cookbook = text[cookbook_start:cookbook_end]
require("recipe completes only after category pages", "当前可升级分类已扫完，本轮完成" in cookbook and "scanState.active = false;" in cookbook)
require("recipe completion preserves long-term target", "长期目标保留为${cfg.targetLevel}" in cookbook and "recipe_target_level" not in cookbook)
require("recipe target change starts a manual round", "source: 'manual'" in text and "active: true" in text)
require("recipe inactive round does not rerun on casual browsing", "本轮已完成，等待下次调度开启新轮次" in text)
require("scheduler starts a fresh recipe round", "if (entry.module === 'recipe') MOD.recipe.startScan('长期调度器');" in text)
require("autopilot starts recipe round once per step", "state.recipePreparedStep !== stepIdx" in text and "MOD.recipe.startScan('自动驾驶');" in text)
require("recipe scans only the upgradable category", "pageInfo.category !== 3" in text and "findUpgradableCategoryLink" in text)
require("recipe persists the exact filtered list page", "scanState.listPath = location.pathname;" in text and "scanState.street = pageInfo.street;" in text)
require("recipe pagination stays in dynamic street category 3", "new RegExp(`^/xz/cookbook_${street}_3_\\\\d+$`)" in text)
return_start = text.index("    returnToList() {")
return_end = text.index("// ----- 12. 守护者", return_start)
recipe_return = text[return_start:return_end]
require("recipe returns through history instead of arbitrary cookbook link", "history.back()" in recipe_return and "/\\/xz\\/cookbook_/" not in recipe_return)

require("scheduler persists fixed plans", "Utils.gset(`sched_${e.id}_nextAt`, e.nextRunAt);" in text)
require("scheduler preserves overdue fixed plans", "e.nextRunAt = saved > 0 ? saved : this.computeFixedNext(e, nowMs);" in text)
require("scheduler preserves overdue dynamic plans", "saved > 0 ? saved : e.computeNext()" in text)
require("scheduler no longer discards overdue plans", "saved > nowMs ? saved" not in text)
require("scheduler start does not call missing init", "this.init();" not in text)
require("scheduler start computes immediately on home", "this.computeAll();\n        this.scheduleNext();" in text)
require("scheduler supports multi-page navigation", "async navigatePhase(phase, currentPath)" in text)
require("scheduler bag route is two-step", "route: [{ text: '仓库', href: '/xz/warehouse' }, { text: '礼包', href: '/xz/warehouse_2_0' }]" in text)
require("scheduler guardian route is two-step", "{ text: '挑战守护者', href: '/xz/guardian' }" in text)
require("scheduler recipe route is dynamic", "hrefPattern: '^/xz/cookbook_\\\\d+_3_1$'" in daily and "target: '/xz/cookbook_8_3_1'" not in daily)
require("scheduler restaurant route uses real href without mutable text", "id: 'restaurant', module: 'restaurant', target: '/xz/restaurant', nav: '餐厅', route: [{ href: '/xz/restaurant' }]" in text)
dynamic = text[text.index("const DYNAMIC_SCHEDULE = ["):text.index("const ALL_ENTRIES")]
require("scheduler mailbox follows restaurant entry", dynamic.index("id: 'restaurant'") < dynamic.index("id: 'mailboxAfterRestaurant'") < dynamic.index("id: 'facility'"))
require("scheduler mailbox uses real homepage inbox href", "id: 'mailboxAfterRestaurant', module: 'mailbox', target: '/xz/mailbox'" in dynamic and "route: [{ text: '邮箱', href: '/xz/mailbox' }]" in dynamic)
require("scheduler mailbox is chained only", "chainedOnly: true" in dynamic and "restaurantLast > mailboxLast" in dynamic and "e.chainedOnly ? e.computeNext()" in text)
require("scheduler forces mailbox immediately after restaurant return", "phase.id === 'restaurant' && isEnabled('mailbox')" in text and "void this.fireToTarget(mailboxEntry);" in text and "确保其它积压任务不能插到两者之间" in text)
restaurant_plan = text.index("{ module: 'restaurant', navSteps:")
mailbox_plan = text.index("{ module: 'mailbox',    navSteps:")
facility_plan = text.index("{ module: 'facility',   navSteps:")
require("autopilot mailbox is immediately after restaurant", restaurant_plan < mailbox_plan < facility_plan and "text: '邮箱'" in text[mailbox_plan:facility_plan] and "hrefMatch: '/xz/mailbox'" in text[mailbox_plan:facility_plan])
require("scheduler supports pattern navigation", "new RegExp(step.hrefPattern).test(href)" in text and "new RegExp(nav.hrefPattern).test(href)" in text)
require("24h schedules have no cumulative jitter", "slot: '24h', jitterMin: 0, jitterMax: 0" in daily and "jitterMax: 60" not in daily)
require("scheduler recomputes all tasks after return", "this.computeAll();\n        this.scheduleNext();" in text)
require("scheduler records completion in server time", "const completedAt = Utils.getServerTime().getTime();" in text and "Utils.gset(`sched_${phase.id}_lastRun`, completedAt);" in text)
require("fixed daily tasks catch up after missed slot", "if (lastDay !== today && next.getTime() <= nowMs) return nowMs + 5000;" in text)

market_start = text.index("id: 'market', module: 'market', target: '/xz/market'")
market_end = text.index("// 餐厅：17-45min", market_start)
market_schedule = text[market_start:market_end]
require("market tracks completion by server hour", "ranThisHour" in market_schedule and "sched_market_lastRun" in market_schedule)
require("market schedules pre-6 on same day", "todaySix.setHours(6, 0, 0, 0);" in market_schedule)
require("market catches up current active hour", "hour <= 23 && !ranThisHour" in market_schedule and "nowMs + 5000" in market_schedule)
require("market schedules post-23 on next day", "tomorrow.setDate(tomorrow.getDate() + 1);" in market_schedule and "tomorrow.setHours(6, 0, 0, 0);" in market_schedule)
require("market removed normalized-date double increment", "next.setHours(next.getHours() + 1)" not in market_schedule)
require("scheduler migration clears every stale plan", "Utils.gset(`sched_${id}_nextAt`, 0);" in text and "scheduler_schema_version', 3" in text)
require("scheduler migration converts legacy local timestamps", "oldLastRun + serverOffset" in text and "ALL_ENTRIES().forEach" in text)
require("scheduler migration resets meal window date", "sched_energy_lastWindow', null" in text and "sched_energy_lastResetDay', null" in text)
require("scheduler watchdog runs every minute", "setInterval(() => this.watchdogTick('60秒巡检'), 60000)" in text)
require("scheduler watchdog wakes on browser resume", "window.addEventListener('focus'" in text and "document.visibilityState === 'visible'" in text and "window.addEventListener('pageshow'" in text)
require("scheduler watchdog resumes active phase", "恢复 ${phase.id}/${phase.state}" in text and "await Router.run();" in text)
require("scheduler watchdog fires overdue home task", "entry.nextRunAt <= nowMs" in text and "await this.fireToTarget(due);" in text)
require("scheduler allows manual browsing before task is due", "手动浏览 ${path}，无到点任务，不打断" in text and "if (due)" in text)
require("scheduler returns home only for due task", "${due.id} 已到点，从 ${path} 返回首页执行" in text and "await this.navigateHome();" in text)
require("scheduler start does not force home", "启动调度器不打断手动浏览" in text and "this.navigateHome();\n      }" not in text[text.index("    start() {"):text.index("    stop(reason", text.index("    start() {"))])
require("due task keeps original time while returning home", "保留原到点时间" in text and "推后 1min" not in text)
require("scheduler keeps timer alive on manual pages", "任何页面都维持计时，但不主动离开手动浏览页" in text and "if (currentPath === '/xz/')" not in text[text.index("// ---- 无 phase：任何页面"):text.index("// ---- phase=navigating")])
require("enabled scheduler restores watchdog after reload", "if (Scheduler.isOn()) Scheduler.startWatchdog();" in text)
require("scheduler prevents watchdog timer double fire", "忽略重复触发 ${entry.id}" in text and "const existingPhase = Utils.gget(PHASE_KEY, null);" in text)

print(f"\nAll regression checks passed: {SCRIPT}")
