from __future__ import annotations

import re
import sys
from pathlib import Path


SCRIPT = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).parents[1] / "梦想小镇日常一体化.user.js"
text = SCRIPT.read_text(encoding="utf-8")


def require(name: str, condition: bool) -> None:
    if not condition:
        raise AssertionError(name)
    print(f"PASS: {name}")


require("v3.67 metadata and shared panel version", "// @version      3.67" in text and "const SCRIPT_VERSION = '3.67';" in text and "v${SCRIPT_VERSION}" in text)
require("panel registers at document start", "// @run-at       document-start" in text)
require("panel reveals only after scheduler is forced open", "panel.style.visibility = 'hidden';" in text and text.count("schedWrap.open = true;") >= 2 and "panel.style.visibility = 'visible';" in text and "requestAnimationFrame(() =>" in text)
require("scheduler status reserves fixed button geometry", "#dxzxx-sched-status{height:110px;max-height:110px" in text)
init_start = text.index("  function init() {")
init_end = text.index("  if (document.readyState", init_start)
init_block = text[init_start:init_end]
require("scheduler list computes before panel becomes visible", init_block.index("Scheduler.computeAll();") < init_block.index("Panel.create();"))
require("panel has no stale hardcoded title", "梦想小镇日常 v3.18" not in text and "梦想小镇日常 v3.20" not in text)
require("panel doubles desktop width", "width:560px" in text and "box-sizing:border-box" in text)
require("panel control rows use two columns", "#dxzxx-rows,#dxzxx-project-rows{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))" in text)
require("panel configuration area uses two columns", 'class="panel-columns"' in text and 'class="panel-column"' in text)
require("panel details default open", text.count("<details open") >= 5)
require("panel action buttons use two columns", 'class="panel-actions"' in text and "grid-template-columns:repeat(2,minmax(0,1fr));gap:0 6px" in text)
require("global stop button is permanent and reserves its row", "⏹ 停止当前操作</button>" in text and "#dxzxx-stop{grid-column:1/-1;}" in text and "dxzxx-stop\" style=\"background:#f44;color:#fff;display:none" not in text)
require("autopilot refresh never inserts or removes global stop", "stopBtn.style.display" not in text)
require("global stop is mouse only", "addEventListener('keydown'" not in text and "e.key === 'Escape'" not in text and "（Esc）" not in text)
require("all remaining non-main feature rows expose action run buttons", text.count('data-run-action="restaurant_') == 3 and 'data-run-action="project_${p.id}"' in text)
require("duplicate recipe learning control is removed", 'data-run-action="recipe_learn"' not in text and 'data-sub="recipe_learn"' not in text and 'recipe_learn:' not in text)
require("all action run buttons use scoped autopilot", "const ACTION_RUN_DEFS = {" in text and "startAction(actionId)" in text and "actionScope: actionId" in text and "actionNavSteps: def.navSteps" in text)
require("scoped restaurant actions do not run siblings", "actionEnabled('restaurant', 'restaurant_cockroach'" in text and "actionEnabled('restaurant', 'restaurant_oil'" in text)
require("scoped daily projects bypass only their own switch", "scope?.startsWith('project_')" in text and "if (scopedProject !== id) return 0;" in text and "actionRun?.projectId === id" in text)
require("repeatable project actions use persistent per-run success progress", "PROJECT_ACTION_RUN_KEY" in text and "recordScopedProjectSuccess" in text and "run.completed" in text and "actionRun?.active" in text)
require("project action target faithfully allows zero", "actionTarget = projectTarget(projectId);" in text and "Math.max(1, projectTarget(id))" not in text)
require("zero-count project action does not stop scheduler or navigate", "projectTarget(projectId) <= 0" in text and "设置为0次，本次不执行" in text and text.index("projectTarget(projectId) <= 0") < text.index("Scheduler.stop(`细项运行 ${actionId}`)"))
require("project action start clears stale pending without clearing daily counts", "repeatableProjectStateKeys" in text and "projectState.pending = null;" in text and "projectState.counts[projectId] = 0" not in text)
require("server once-only projects keep all-day completion semantics", "if (['npc', 'number'].includes(id)) return Math.max(0, target - (state.counts[id] || 0));" in text and "fist: 'bar', cup: 'bar', number: 'bar'" not in text)
require("extra wish records a scoped success after confirmed refresh", "recordScopedProjectSuccess('extraWish');" in text and text.index("state.counts.extraWish =") < text.index("recordScopedProjectSuccess('extraWish');"))
require("extra wish stock is scoped to the real button sibling", "btn?.nextElementSibling?.textContent" in text and "stockText.match(/拥有\\s*(\\d+)\\s*个/)" in text and "/许愿果[^\\d]*0/.test(text)" not in text)
require("project action session is cleared on stop and stale initialization", text.count("Utils.gset(PROJECT_ACTION_RUN_KEY, null);") >= 4 and "if (!AutoPilot.isOn()) Utils.gset(PROJECT_ACTION_RUN_KEY, null);" in text)
require("panel scheduler information uses freed space", "#dxzxx-sched-status{height:110px;max-height:110px" in text)
require("scheduler detail omits highlighted next or running entry", "const highlightedId = phase?.state === 'running' ? phase.id : next?.id;" in text and "const upcoming = all.filter" in text and "const top5 = upcoming.slice(0, 6);" in text)
require("panel falls back to one column on narrow screens", "@media (max-width:620px)" in text and "grid-template-columns:1fr" in text)
require("panel enlarges font while overriding site line height", "font-size:12px;line-height:1.25;width:560px" in text and "font-size:12px;line-height:1.2;" in text)
require("panel title shows learned self restaurant id", "自己餐厅id已获取：${selfId}" in text and "自己餐厅id未获取" in text and 'class="self-restaurant-id"' in text)
require("autopilot title refresh preserves self id", text.count("Panel.titleHtml(") >= 2 and "Panel.refreshAutopilotUI();" in text)
require("panel scheduler inner box overrides site line height", "#dxzxx-sched-wrap>div{line-height:1.25;}" in text)
top_start = text.index('class="panel-columns"')
daily_ui = text.index("每日项目（早饭后执行）", top_start)
module_ui = text.index("自动驾驶功能开关（按执行顺序）", daily_ui)
require("panel orders common controls daily projects then module switches", top_start < daily_ui < module_ui)
require("panel merges duplicate autopilot preview into switches", "自动驾驶流程（${AutoPilot.PLAN.length} 步）" not in text and "dxzxx-plan-list" not in text)
require("panel renders autopilot steps in actual order with merged numbering", "AutoPilot.PLAN.forEach((step, index) =>" in text and "let displayStep = 0;" in text and "displayStep++;" in text)
require("panel merges restaurant and mailbox into one clean numbered row", "if (step.module === 'mailbox') return;" in text and "GROUP_RUN_DEFS.restaurantAndMailbox.modules.join(',')" in text and "${displayStep}. 餐厅管理与系统邮箱</label>" in text and "含系统邮箱，见左上子开关" not in text)
require("panel groups daily projects as one continuously numbered item", "const dailyProjectModules = GROUP_RUN_DEFS.dailyProjects.modules;" in text and "${displayStep}. 每日项目" in text and "见上方每日项目配置" in text)
require("grouped daily-project row highlights all five internal steps", "row.dataset.modules = dailyProjectModules.join(',');" in text and "modules.includes(currentModule)" in text)
require("daily project row restores one-click selected run", "data-run-group=\"dailyProjects\"" in text and "AutoPilot.startGroup(button.dataset.runGroup);" in text)
daily_group_start = text.index('row.innerHTML = `<label>${displayStep}. 每日项目')
daily_group_end = text.index('rows.appendChild(row);', daily_group_start)
daily_group_row = text[daily_group_start:daily_group_end]
require("daily project reference precedes aligned run button", daily_group_row.index('class=\"plan-ref\"') < daily_group_row.index('class=\"group-run\"'))
require("daily projects restore a default-on master switch", "mod_dailyProjects_enabled" in text and 'data-id=\"dailyProjects\"' in daily_group_row and "Utils.gget('mod_dailyProjects_enabled', true)" in text)
require("daily master gates scheduled and full autopilot projects", "return Utils.gget('mod_dailyProjects_enabled', true) &&" in text)
require("daily reset note moves into the section title", '<summary>每日项目（早饭后执行）<span class=\"summary-note\">按服务器06:00重置；次数按成功动作记账；搬家不执行</span></summary>' in text and '<div class=\"label\">按服务器06:00重置' not in text)
require("restaurant merged row runs both modules", "restaurantAndMailbox: { label: '餐厅管理与系统邮箱', modules: ['restaurant', 'mailbox'] }" in text and "data-run-group=\"restaurantAndMailbox\"" in text)
require("merged module switches highlight current autopilot module", "row.dataset.module = m.id;" in text and "modules.includes(currentModule)" in text)
require("recipe target redundant label removed", '<div class="label">目标等级</div>' not in text)
require("every visible module switch has single run button", 'class="single-run" data-run-module="${m.id}"' in text and "panel.querySelectorAll('[data-run-module]')" in text)
require("single run follows real autopilot route", "startSingle(moduleId)" in text and "const stepIndex = this.PLAN.findIndex" in text and "setTimeout(() => this.continue(), 300);" in text)
require("single run bypasses persistent module switch", "if (!state.singleModule && !isEnabled(step.module))" in text)
require("single run stops after one module", "if (state.singleModule)" in text and "✓ 单项运行完成" in text and "this.stop(`${label} 单项完成`);" in text)
require("single and grouped runs restore only previous scheduler state", "resumeSchedulerAfterSingle: schedulerWasOn" in text and "const scopedRun = !!(previousState.singleModule || previousState.singleGroup);" in text and "scopedRun ? !!previousState.resumeSchedulerAfterSingle : true" in text)
require("group run requires contiguous plan modules", "startGroup(groupId)" in text and "index !== indices[i - 1] + 1" in text)
require("group run executes only enabled selections", "def.modules.some(moduleId => isEnabled(moduleId))" in text and "if (!state.singleModule && !isEnabled(step.module))" in text)
require("group run stops at its final module", "state.singleEndStepIndex" in text and "✓ 合并运行完成" in text and "this.stop(`${label} 合并完成`);" in text)
require("cockroach panel icon uses the game asset instead of unsupported emoji", "class=\"panel-icon\" src=\"/readImg/xz_cockroach\"" in text and "🪳 自动打蟑螂" not in text)
require("server time accepts current and legacy labels", "/(?:驯鹿|家园)报时[：:]/" in text)
require("server clock advances from static page sample", "_serverClockCapturedAt" in text and "localNow - this._serverClockCapturedAt" in text)

coupon_ids = re.search(r"PROP_IDS:\s*\[([^\]]+)\]", text)
require("food coupon whitelist exists", coupon_ids is not None)
ids = [int(value) for value in re.findall(r"\d+", coupon_ids.group(1))]
require("food coupon uses only legacy 8 ids", ids == [244, 21, 22, 23, 24, 25, 245, 224])
require("food coupon matches real warehouse", "p === '/xz/warehouse'" in text)
require("food coupon matches current exchange path", "(?:prop_)?food_random_" in text)
require("food coupon reads remaining quantity", "const remaining = quantityMatch ? parseInt(quantityMatch[1], 10) : null;" in text)
require("food coupon returns only after zero", "if (remaining === 0)" in text and "已归零，回仓库" in text)
require("food coupon uses exchange while nonzero", "if (exchangeBtn && remaining !== 0)" in text)
require("food coupon has no text fallback", "名字含\"食材\"/\"调料\"/\"随机\"" not in text)
daily_start = text.index("const DAILY_SCHEDULE = [")
daily_end = text.index("const DYNAMIC_SCHEDULE = [")
daily = text[daily_start:daily_end]
require("food coupon is in daily scheduler", "id: 'foodCoupon', module: 'foodCoupon'" in daily)

require("bag matches current result URL", r"/\/xz\/(?:prop|open)_bag_/" in text)
require("bag clicks only first item", "Utils.click(links[0]);" in text)
require("bag no longer clickAll", "Utils.clickAll(links, '礼包')" not in text)
require("bag completes only when empty", "礼包: 无可用" in text and "return true;" in text)

compound_start = text.index("  MOD.foodCompound = {")
compound_end = text.index("  // ----- 5. 设施安装", compound_start)
compound = text[compound_start:compound_end]
require("food compound follows dynamic first level-one item", "a[href^=\"/xz/food_compound_\"]" in compound and "find(a => /^\\/xz\\/food_compound_\\d+$/.test" in compound and "/xz/food_compound_3" not in compound)
require("food compound clicks only real all button", "a.textContent.trim() === '全部合成'" in compound and "^doFoodCompound\\(\\d+,50\\)$" in compound)
require("food compound records before its only click", compound.index("Utils.gset(this.STATE_KEY") < compound.index("Utils.click(allButton)") and "本轮已经点击过“全部合成”" in compound)
require("food compound ignores casual manual browsing", "requiresScheduled: true" in compound and "非调度/自动驾驶阶段，不接管手动浏览" in compound)
require("food compound retry token is tied to meal completion", "scheduler-energy:${Utils.gget('sched_energy_lastRun', 0)}" in compound)

require("autopilot removed same-page advance", "session.lastPage" not in text and "5s 内重复" not in text)
require("autopilot clears emergency stop on start", "Utils.gset('autopilot_emergency_stop', false);" in text)
require("autopilot continues disabled steps on home", "setTimeout(() => this.continue(), 700);" in text)
require("autopilot requires explicit completion", "if (completed === true)" in text)
require("router yields plan modules", "由 AutoPilot 独占，Router 不重复执行" in text)
require("router does not mark action-in-progress complete", "仍有后续动作，不写完成标志" in text)
require("autopilot food coupon route is real", "{ module: 'foodCoupon', navSteps: [{ text: '仓库'," in text)
require("autopilot includes market purchase", "{ module: 'market',     navSteps: [{ text: '菜场'," in text)
require("autopilot includes merged NPC visits from food god", "{ module: 'dailyNpc',   navSteps: [{ text: '食神'," in text)
require("autopilot includes daily friend projects", "{ module: 'dailyFriend', navSteps: [{ text: '好友'," in text)
require("autopilot includes daily bar projects", "{ module: 'dailyBar',   navSteps: [{ text: '广场'," in text)
require("autopilot includes restaurant visitor luck", "{ module: 'dailyLuck',  navSteps: [{ text: '来访'," in text)
require("autopilot includes extra wish project", "{ module: 'extraWish',  navSteps: [{ text: '许愿'," in text)
require("autopilot includes vitality claims", "{ module: 'vitality',   navSteps: [{ text: '今日活跃'," in text)
require("merged autopilot switches describe execution order", "自动驾驶功能开关（按执行顺序）" in text)
require("autopilot recipe route is dynamic", "{ text: '可升级'," in text and "hrefPattern: '^/xz/cookbook_\\\\d+_3_1$'" in text)
require("autopilot is labelled one-shot", "🚀 立即跑一轮全套" in text and "🚀 自动跑全套日常" not in text)

require("guardian reads inventory only from the explosive missile row", "p.querySelector('a[href=\"/xz/prop_82\"]')" in text and "parseGuardianInventory()" in text)
require("guardian uses ten shots above one thousand hp and single below", "parseGuardianHp()" in text and "hp > 1000 ? 10 : 1" in text and "guardianLaunch(82,${count})" in text)
require("guardian has a twenty minute cross-page lifetime", "maxPhaseAgeMs: 20 * 60000" in text and "MOD[phase.module]?.maxPhaseAgeMs" in text)
require("v366 retries a guardian falsely completed by old timeout", "v366_guardian_timeout_retry_migrated" in text and "sched_guardian_lastRun', 0" in text and "sched_guardian_nextAt', 0" in text)
require("guardian can replenish repeatedly after verified stock is consumed", "purchase?.verifiedAt && have < purchase.after" in text and text.count("Utils.gset(this.PURCHASE_KEY, null);") >= 4 and "recentlyVerified" not in text)
require("guardian production replenishment is 300 below 200", "REPLENISH_BELOW: 200" in text and "BUY_COUNT: 300" in text and "buyByActivity(0,82,0)" in text)
require("guardian parses both inventories without zero fallback", "parseGuardianInventory()" in text and "parseStoreInventory()" in text and "拥有数量\\s*[：:]\\s*(\\d+)" in text and "have === null" in text)
require("guardian records and verifies one purchase", "PURCHASE_KEY: 'guardian_missile_purchase'" in text and "before: have" in text and "have >= purchase.before + this.BUY_COUNT" in text and "12小时内不重复购买" in text)
require("guardian supports current and legacy quantity input ids", "getElementById('buyNum') || document.getElementById('buy_num')" in text)
require("guardian verifies same-page purchases without scheduler running stall", "for (let i = 0; i < 12; i++)" in text and "after >= have + this.BUY_COUNT" in text and "同页购买验证成功" in text and "本轮安全结束" in text)
guardian_start = text.index("  MOD.guardian = {")
guardian_end = text.index("  // ==================== 可配置每日项目", guardian_start)
guardian_block = text[guardian_start:guardian_end]
require("guardian ignores casual manual store browsing", "requiresScheduled: true" in guardian_block)
require("egg action returns in-progress", "扭蛋: 已扭" in text and "return false;" in text)
require("daily projects exclude moving", "DAILY_PROJECT_DEFS" in text and "project_move" not in text)
require("daily project labels show vitality recommendations", "打蟑螂（推荐15次）" in text and "翻橱柜（推荐20次）" in text and "点赞/被赞（推荐5次）" in text)
require("daily project counts persist on input and change", "addEventListener('input', saveProjectCount)" in text and "addEventListener('change', saveProjectCount)" in text)
require("daily projects use 6am game day", "date.getTime() - 6 * 3600000" in text)
require("daily friend actions are configurable", "['like', 'dig', 'roach'].some" in text and "DailyProjectState.remaining(type, state)" in text)
require("daily bar actions are configurable", "DailyProjectState.remaining('fist'" in text and "DailyProjectState.remaining('cup'" in text and "DailyProjectState.remaining('number'" in text)
require("daily NPC project is one complete round", "拜访NPC（推荐1轮）" in text and "['god', 'garden', 'deer', 'annie', 'wenjie'].every" in text and "本轮完成 1/1" in text)
require("daily NPC round includes all five visits", "visitHere('god', '食神')" in text and "visitHere('garden', '菜园姐')" in text and "visitHere('deer', '阿鹿')" in text and "visitHere('annie', '安妮')" in text and "visitHere('wenjie', '雯姐')" in text)
require("daily NPC association route returns through square", "goRequired('/xz/association')" in text and "location.pathname === '/xz/association'" in text and "goRequired('/xz/square')" in text and "!state.visited.includes('annie')" in text)
require("daily NPC crosses regions through real home route", "!state.visited.includes('god')" in text and "!state.visited.includes('garden')" in text and "return goRequired('/xz/');" in text and "return goRequired('/xz/market');" in text)
require("daily NPC missing links never report completion", "找不到真实下一跳" in text and "绝不能误报整个模块完成" in text and "return (await go('/xz/market')) ? false : true;" not in text)
require("v354 resets stale NPC progress once", "v354_npc_route_reset" in text and "Utils.gset('project_state_npc', null);" in text)
require("food god has no standalone module or schedule", "MOD.god =" not in text and "id: 'god',     module: 'god'" not in daily)
require("single NPC run starts from food god", "project_npc: { module: 'dailyNpc', navSteps: [{ text: '食神', hrefMatch: '/xz/god' }] }" in text)
require("daily NPC migrates v3.33 partial count", "v334_npc_round_migrated" in text and "state.counts.npc = complete ? 1 : 0;" in text)
require("daily NPC target is capped to one round", "id === 'npc' ? 1 : id === 'luck' ? 3 : 500" in text)
require("daily NPC input is capped to one round", "max=\"${p.id === 'npc' ? 1 : p.id === 'luck' ? 3 : 500}\"" in text)
require("daily NPC is independent from paid market", "module: 'dailyNpc'" in text and "['dailyFriend', 'dailyBar', 'dailyNpc', 'dailyLuck', 'extraWish']" in text)
luck_start = text.index("  MOD.dailyLuck = {")
luck_end = text.index("  MOD.extraWish = {", luck_start)
luck = text[luck_start:luck_end]
require("daily luck is configurable and capped at three", "沾光（推荐3次）" in text and "id === 'luck' ? 3" in text and "p.id === 'luck' ? 3" in text)
require("daily luck syncs exact server progress", "今日已沾光[：:\\s]*(\\d+)\\s*\\/\\s*3" in luck and "state.counts.luck = serverCount;" in luck)
require("daily luck completes only on page-verified three of three", "if (serverCount >= 3)" in luck and "Utils.gset('luck_verified_day', gameDayKey());" in luck and "来访页已验证“今日已沾光：3 / 3次”" in luck and "if ((state.counts.luck || 0) >= 3) return true;" not in luck)
require("daily luck refreshes stale back-cache before verification", "state.verifyFresh = succeeded;" in luck and "if (state.verifyFresh)" in luck and "state.verifyFresh = false;" in luck and "location.reload();" in luck and "刷新一次复核服务器N/3" in luck)
require("daily luck single-run still honors configured count", "activeActionScope('dailyLuck') === 'project_luck'" in luck and "DailyProjectState.remaining('luck', state) <= 0" in luck and "全天完成仍以来访页3/3为准" in luck)
require("daily luck follows only current deer or fool visits", "!/正在/.test(rowText)" in luck and "!/阿鹿|阿呆/.test(rowText)" in luck and "state.tried.includes(restaurantId)" in luck)
require("daily luck clicks the real restaurant button", "addLuck(\"${restaurantId}\")" in luck and "a.textContent.trim() === '沾光'" in luck and "recordScopedProjectSuccess('luck');" in luck)
require("daily luck exposes a scoped single-run route", "project_luck: { module: 'dailyLuck', navSteps: [{ text: '来访', hrefMatch: '/xz/come_log' }] }" in text and "luck: 'luck'" in text)
require("daily luck removes duplicate fixed catch-up entries", "id: 'dailyLuck1031'" not in daily and "id: 'dailyLuck1131'" not in daily)
require("friend list prioritizes roach markers", "img[src=\"/readImg/xz_cockroach\"]" in text and "const marked = links.filter(hasRoachMark);" in text)
require("friend floors follow roach markers", "const markedRoachFloor = floorLinks.find" in text and "Utils.click(floorToVisit);" in text)
require("autopilot hands off to scheduler", "自动驾驶: 已交接长期循环调度器" in text and "Scheduler.start();" in text)
require("global stop does not restart scheduler", "AutoPilot.stop(reason, { resumeScheduler: false })" in text)
require("global stop clears active phases and latches automation", "stopCurrentOperation(reason" in text and "Utils.gset('operation_stopped', true);" in text and "Utils.gset(PHASE_KEY, null);" in text)
require("global stop blocks pending clicks and router resumes", "总停止锁已启用，阻止脚本继续点击" in text and "总停止锁已启用，跳过所有自动动作" in text)
require("explicit starts release global stop latch", text.count("Utils.gset('operation_stopped', false);") >= 4)
require("vitality claims first available award", "a[onclick^='addVitalityAward']" in text and "今日活跃: 领取第一项" in text)
require("morning and evening reward sweeps exist", "vitalityMorning" in daily and "vitalityEvening" in daily and "seasonMorning" in daily and "seasonEvening" in daily and "eggMorning" in daily and "eggEvening" in daily)
require("temporary reward routes are optional", "optional: true" in daily and "可选入口" in text)
require("scheduled modules are isolated", "与当前调度阶段" in text and "mod.requiresScheduled" in text)

require("market discount is exactly 666", "DISCOUNT_PRICE: 666" in text and "price === this.CONFIG.DISCOUNT_PRICE" in text)
require("market discount dedupes by server hour", "market_last_discount_hour" in text)
require("market parses current daily market rows", "a[onclick^='buyDayFood']" in text and r"buyDayFood\((\d+),(\d+),(\d+)\)" in text)
require("market keeps old staple thresholds", "LEVEL1_TARGET: 950" in text and "LEVEL1_MAX_PRICE: 519" in text and "LEVEL2_TARGET: 950" in text and "LEVEL2_MAX_PRICE: 2650" in text and "FORCE_BUY_2: ['鸡肉', '猪肉']" in text)
require("market claims Tuesday reserve coupon first", "a[onclick^='getEverydayReserve']" in text and "已领取周二日常食材预定券" in text)
require("market claim remains in progress across refresh", "Utils.click(reserveClaim);" in text and "return false;" in text)
market_run = text[text.index("MOD.market = {"):text.index("// ----- 7. 食材券")]
require("market explicitly completes when no purchase remains", "市场: 无常驻菜" in market_run and "市场: 常驻菜全部达标" in market_run and market_run.count("return true;") >= 5)
require("market purchase remains in progress across refresh", "Utils.click(foodToBuy.buyButton);" in market_run and "return false;" in market_run)
require("router respects explicit in-progress result", "(!inPlan && completed !== false)" in text)
require("facility threshold restored to 5", "MIN_COUNT: 5" in text)
facility_run = text[text.index("MOD.facility = {"):text.index("// ----- 5. 食材采购")]
require("facility buys exactly 10 below threshold", "BUY_COUNT: 10" in facility_run and "have < this.MIN_COUNT" in facility_run and "购买${this.BUY_COUNT}个" in facility_run)
require("facility store requires explicit inventory", "parseStoreInventory()" in facility_run and r"拥有数量\s*[：:]\s*(\d+)" in facility_run)
require("facility has no arbitrary purchase fallback", "备用购买" not in facility_run and "anyBuy" not in facility_run)
require("manual facility shop remains safely enabled", "facility_manual_purchase_${propId}" in facility_run and "最近已尝试购买但库存仍为" in facility_run)
require("facility cycle renews each installed target once", 'a[onclick="addFacility(${t.slot})"]' in facility_run and "state.renewed.push(t.propId)" in facility_run)
require("facility cycle checks all three real shop links", "state.checked.includes(t.propId)" in facility_run and "点击 ${next.name} 名称进入商店检查库存" in facility_run)
require("facility schedule is fixed at 12h", "lastRun + 12 * 3600000" in text and "runMs: 180000" in text)
require("facility schedule migration drops stale plan", "v342_facility_schedule_migrated" in text and "sched_facility_nextAt', 0" in text)
require("restaurant oil has independent switch", "restaurant_oil: true" in text and "restaurant_oil', true" in text)
require("restaurant oil threshold is 14000", "if (cur < 14000)" in text and "if (cur < 11000)" not in text)
require("restaurant roach has per-cycle failure stop and hard cap", "MAX_ROACH_ATTEMPTS: 20" in text and "restaurant_roach_attempts" in text and "restaurant_roach_cycle_blocked" in text and "只停止本轮" in text)
require("restaurant floor detection cannot oscillate between siblings", "el.previousElementSibling || el.nextElementSibling" not in text and ".some(tryMatch);" in text)
require("scheduler expires persisted phases before module execution", "recoverExpiredPhase(path)" in text and text.index("recoverExpiredPhase(path)") < text.index("const activePhase = Scheduler.isOn()"))
require("expired restaurant phase stops only current roach cycle", "超时自救只停止本轮打蟑螂" in text and "Utils.gset('restaurant_remaining_floors', []);" in text)
require("restaurant roach defaults on and migrates prior forced-off value once", "restaurant_cockroach: true" in text and "v348_restaurant_cockroach_default_on" in text and "Utils.gset('restaurant_cockroach', true);" in text)
require("restaurant roach runtime never permanently disables itself", "Utils.gset('restaurant_cockroach', false);" not in text)
require("manually enabling restaurant roach resets the current-cycle stop", "sub === 'restaurant_cockroach' && !cur" in text and "Utils.gset('restaurant_roach_cycle_blocked', false);" in text)
require("restaurant master switch is clearly labelled", "餐厅管理（总开关）" in text)
restaurant_start = text.index("MOD.restaurant = {")
restaurant_end = text.index("// ----- 10.", restaurant_start)
restaurant_run = text[restaurant_start:restaurant_end]
require("own restaurant learns id from two real sources", "SELF_ID_KEY: 'self_restaurant_id'" in restaurant_run and "titleId" in restaurant_run and "floorIds" in restaurant_run and "titleId !== floorId" in restaurant_run)
require("own restaurant rejects friend uid floors", "isSelfFloor(path)" in restaurant_run and "不是自己的餐厅" in restaurant_run and "保持只读" in restaurant_run)
require("own restaurant floor navigation is scoped to self id", "h === `/xz/restaurant_${selfId}_${floor}`" in restaurant_run)
require("own restaurant actions require an explicit run phase", "requiresScheduled: true" in restaurant_run)
require("router learns self id read-only on manual overview", "if (path === '/xz/restaurant') MOD.restaurant.learnSelfId();" in text)
daily_friend_start = text.index("MOD.dailyFriend = {")
daily_friend_end = text.index("// 每日 NPC", daily_friend_start)
daily_friend_run = text[daily_friend_start:daily_friend_end]
require("daily friend still owns all three friend actions", "addLikeOne" in daily_friend_run and "killCockroach" in daily_friend_run and "digOne" in daily_friend_run)
require("daily friend still traverses friend pages", "下一页" in daily_friend_run and r"friend_0_\d+" in daily_friend_run and "state.visited" in daily_friend_run)
restaurant_ui_start = text.index("<summary>餐厅子开关</summary>")
restaurant_ui_end = text.index("<summary>食谱升级配置</summary>", restaurant_ui_start)
restaurant_ui = text[restaurant_ui_start:restaurant_ui_end]
require("own restaurant direct roach action runs before floor scan", "async killCurrentRoach()" in restaurant_run and "a[onclick^='killCockroach']" in restaurant_run and restaurant_run.index("killCurrentRoach())") < restaurant_run.index("detectInfectedFloors()"))
require("own restaurant dig UI and runtime are removed", "自动翻橱柜" not in restaurant_ui and "digOne" not in restaurant_run and "MAX_DIG_ATTEMPTS" not in restaurant_run)
require("v337 clears stale restaurant dig settings", "v337_restaurant_dig_removed" in text and "Utils.gset('restaurant_dig', false);" in text)
require("restaurant mailbox switch defaults on", "restaurant_mailbox: true" in text and "餐厅后领取系统邮件" in text)
require("mailbox scans only system first page", "p === '/xz/mailbox' || p === '/xz/mailbox_0_1'" in text and "mailbox_0_2" not in text)
require("mailbox claim is exact and attachment-only", "text === '领取'" in text and r"/^getMailProp\(\d+,\s*0\);?$/" in text)
require("mailbox claims one gift per refresh", "Utils.click(claim);" in text and "领取第一份系统礼物，刷新后继续检查" in text and "return false;" in text)
require("mailbox completes only when no claim remains", "系统首页没有可领取礼物" in text and "系统礼物已检查" in text)
require("recipe default is off", text.count("recipe_target_level', 'off'") >= 2)
require("recipe uses middle-tier name in UI", '<option value="中品">升级到中品</option>' in text and "升级到中品（原特色）" not in text)
require("recipe keeps legacy middle-tier parser alias", "'中品': 1, '特色': 1" in text)
require("recipe migrates legacy target", "recipe_target_level', 'off') === '特色'" in text and "recipe_target_level', '中品'" in text)
require("recipe parses plain-text detail level", "食谱等级[:：]\\s*(金牌(?:\\d+级)?|极品|上品|中品|特色|普通)" in text)
detail_start = text.index("async processDetail()")
detail_end = text.index("// 找普通升级按钮", detail_start)
detail = text[detail_start:detail_end]
require("recipe checks target before upgrade button", "currentLevel >= targetLevel" in detail and detail.index("currentLevel >= targetLevel") < detail.index("findNormalUpgradeButton"))
require("recipe fails closed when level is unknown", "currentLevel === undefined || targetLevel === undefined" in detail and "等级解析失败，已跳过" in detail)
require("recipe scan skips blocked items", "scanStateKey: 'recipe_scan_state'" in text and "blocked.includes(link.getAttribute('href') || '')" in text)
require("recipe continues after insufficient materials", "材料或条件不足" in text and "继续扫描其它菜品" in text)
cookbook_start = text.index("async processCookbook()")
cookbook_end = text.index("// 找可升级项", cookbook_start)
cookbook = text[cookbook_start:cookbook_end]
require("recipe completes only after category pages", "当前可升级分类已扫完，本轮完成" in cookbook and "scanState.active = false;" in cookbook)
require("recipe completion preserves long-term target", "长期目标保留为${cfg.targetLevel}" in cookbook and "recipe_target_level" not in cookbook)
require("recipe target change starts a manual round", "source: 'manual'" in text and "active: true" in text)
require("recipe inactive round does not rerun on casual browsing", "本轮已完成，等待下次调度开启新轮次" in text)
require("scheduler starts a fresh recipe round", "if (entry.module === 'recipe') MOD.recipe.startScan('长期调度器');" in text)
require("autopilot starts recipe round once per step", "state.recipePreparedStep !== stepIdx" in text and "MOD.recipe.startScan('自动驾驶');" in text)
require("recipe scans only the upgradable category", "pageInfo.category !== 3" in text and "findUpgradableCategoryLink" in text)
require("recipe persists the exact filtered list page", "scanState.listPath = location.pathname;" in text and "scanState.street = pageInfo.street;" in text)
require("recipe pagination stays in requested dynamic category", "findNextPageByCategory(street, category)" in text and "new RegExp(`^/xz/cookbook_${street}_${category}_\\\\d+$`)" in text)
require("recipe upgrade includes unlearned items from upgradable category", "const isUnlearned = /未学习|尚未学习|未学/.test(lvlText);" in text and "const cur = isUnlearned ? -1" in text)
require("recipe always learns before parsing and upgrading", "可升级分类发现未学习食谱，已先点学习" in detail and detail.index("const learnBtn") < detail.index("const currentLevelText"))
return_start = text.index("    returnToList() {")
return_end = text.index("// ----- 12. 守护者", return_start)
recipe_return = text[return_start:return_end]
require("recipe returns through history instead of arbitrary cookbook link", "history.back()" in recipe_return and "/\\/xz\\/cookbook_/" not in recipe_return)

require("scheduler persists fixed plans", "Utils.gset(`sched_${e.id}_nextAt`, e.nextRunAt);" in text)
require("scheduler preserves overdue fixed plans", "e.nextRunAt = saved > 0 ? saved : this.computeFixedNext(e, nowMs);" in text)
require("scheduler preserves overdue dynamic plans", "saved > 0 ? saved : e.computeNext()" in text)
require("scheduler no longer discards overdue plans", "saved > nowMs ? saved" not in text)
require("scheduler start does not call missing init", "this.init();" not in text)
require("scheduler start computes immediately on home", "this.computeAll();\n        this.scheduleNext();" in text)
require("scheduler supports multi-page navigation", "async navigatePhase(phase, currentPath)" in text)
require("scheduler bag route is two-step", "route: [{ text: '仓库', href: '/xz/warehouse' }, { text: '礼包', href: '/xz/warehouse_2_0' }]" in text)
require("scheduler guardian route is two-step", "{ text: '挑战守护者', href: '/xz/guardian' }" in text)
require("scheduler recipe route is dynamic", "hrefPattern: '^/xz/cookbook_\\\\d+_3_1$'" in daily and "target: '/xz/cookbook_8_3_1'" not in daily)
require("scheduler restaurant route uses real href without mutable text", "id: 'restaurant', module: 'restaurant', target: '/xz/restaurant', nav: '餐厅', route: [{ href: '/xz/restaurant' }]" in text)
dynamic = text[text.index("const DYNAMIC_SCHEDULE = ["):text.index("const ALL_ENTRIES")]
require("daily luck checks every hour at minute 31", "id: 'dailyLuckHourly', module: 'dailyLuck'" in dynamic and "setHours(10, 31, 0, 0)" in dynamic and "setHours(hour + 1, 31, 0, 0)" in dynamic)
require("daily luck catches up only current hour", "sched_dailyLuckHourly_lastRun" in dynamic and "ranThisHour" in dynamic and "nowMs + 5000" in dynamic and "dailyLuck1031" not in dynamic and "dailyLuck1131" not in dynamic)
require("daily luck stops scheduling after page verification", "luck_verified_day" in dynamic and "return nextDayStart();" in dynamic)
require("food compound is chained after every completed meal", "id: 'foodCompoundAfterEnergy', module: 'foodCompound'" in dynamic and "energyLast > compoundLast" in dynamic and "chainedOnly: true" in dynamic)
require("scheduler launches food compound immediately after energy", "phase.id === 'energy' && isEnabled('foodCompound')" in text and "void this.fireToTarget(compoundEntry);" in text)
require("scheduler mailbox follows restaurant entry", dynamic.index("id: 'restaurant'") < dynamic.index("id: 'mailboxAfterRestaurant'") < dynamic.index("id: 'facility'"))
require("scheduler mailbox uses real homepage inbox href", "id: 'mailboxAfterRestaurant', module: 'mailbox', target: '/xz/mailbox'" in dynamic and "route: [{ text: '邮箱', href: '/xz/mailbox' }]" in dynamic)
require("scheduler mailbox is chained only", "chainedOnly: true" in dynamic and "restaurantLast > mailboxLast" in dynamic and "e.chainedOnly ? e.computeNext()" in text)
require("scheduler forces mailbox immediately after restaurant return", "phase.id === 'restaurant' && isEnabled('mailbox')" in text and "void this.fireToTarget(mailboxEntry);" in text and "确保其它积压任务不能插到两者之间" in text)
restaurant_plan = text.index("{ module: 'restaurant', navSteps:")
mailbox_plan = text.index("{ module: 'mailbox',    navSteps:")
facility_plan = text.index("{ module: 'facility',   navSteps:")
require("autopilot mailbox is immediately after restaurant", restaurant_plan < mailbox_plan < facility_plan and "text: '邮箱'" in text[mailbox_plan:facility_plan] and "hrefMatch: '/xz/mailbox'" in text[mailbox_plan:facility_plan])
autopilot_plan = text[text.index("  const AutoPilot = {"):text.index("    stateKey: 'autopilot_state'")]
autopilot_modules = re.findall(r"\{ module: '([^']+)'", autopilot_plan)
require("autopilot moves restaurant to step 2 and mailbox to step 3", autopilot_modules[:4] == ['signIn', 'restaurant', 'mailbox', 'wish'])
require("autopilot merges food god into NPC and includes luck in daily projects", len(autopilot_modules) == 21 and autopilot_modules[4:12] == ['box', 'foodCoupon', 'market', 'dailyNpc', 'dailyFriend', 'dailyBar', 'dailyLuck', 'extraWish'] and 'god' not in autopilot_modules)
energy_index = autopilot_modules.index('energy')
require("autopilot puts food compound immediately after energy", autopilot_modules[energy_index:energy_index + 2] == ['energy', 'foodCompound'])
require("autopilot ends with two seasonal activities then vitality", autopilot_modules[-3:] == ['season', 'egg', 'vitality'])
require("scheduler supports pattern navigation", "new RegExp(step.hrefPattern).test(href)" in text and "new RegExp(nav.hrefPattern).test(href)" in text)
require("guardian uses daily 06:05 plus up to ten minutes", "id: 'guardian'" in daily and "slot: '6:05', jitterMin: 0, jitterMax: 10" in daily)
require("recipe uses daily 08:10 plus up to ten minutes", "id: 'recipe'" in daily and "slot: '8:10', jitterMin: 0, jitterMax: 10" in daily)
require("guardian and recipe no longer use drifting 24h slots", "slot: '24h'" not in daily)
require("guardian recipe daily migration exists", "v365_guardian_recipe_daily_migrated" in text and "sched_guardian_nextAt', 0" in text and "sched_recipe_nextAt', 0" in text)
require("scheduler recomputes all tasks after return", "this.computeAll();\n        this.scheduleNext();" in text)
require("scheduler records completion in server time", "const completedAt = Utils.getServerTime().getTime();" in text and "Utils.gset(`sched_${phase.id}_lastRun`, completedAt);" in text)
require("fixed daily tasks catch up after missed slot", "if (lastDay !== today && next.getTime() <= nowMs) return nowMs + 5000;" in text)

market_start = text.index("id: 'market', module: 'market', target: '/xz/market'")
market_end = text.index("// 餐厅：17-45min", market_start)
market_schedule = text[market_start:market_end]
require("market tracks completion by server hour", "ranThisHour" in market_schedule and "sched_market_lastRun" in market_schedule)
require("market schedules pre-6 on same day", "todaySix.setHours(6, 0, 0, 0);" in market_schedule)
require("market catches up current active hour", "hour <= 23 && !ranThisHour" in market_schedule and "nowMs + 5000" in market_schedule)
require("market schedules post-23 on next day", "tomorrow.setDate(tomorrow.getDate() + 1);" in market_schedule and "tomorrow.setHours(6, 0, 0, 0);" in market_schedule)
require("market removed normalized-date double increment", "next.setHours(next.getHours() + 1)" not in market_schedule)
require("scheduler migration clears every stale plan", "Utils.gset(`sched_${id}_nextAt`, 0);" in text and "scheduler_schema_version', 3" in text)
require("scheduler migration converts legacy local timestamps", "oldLastRun + serverOffset" in text and "ALL_ENTRIES().forEach" in text)
require("scheduler migration resets meal window date", "sched_energy_lastWindow', null" in text and "sched_energy_lastResetDay', null" in text)
require("v360 migrates fixed luck schedules", "v360_luck_schedule_migrated" in text and "['dailyLuck1031', 'dailyLuck1131', 'dailyLuckHourly']" in text)
require("v361 immediately rechecks potentially missed three of three", "v361_luck_fresh_verify_migrated" in text and "sched_dailyLuckHourly_lastRun', 0" in text and "sched_dailyLuckHourly_nextAt', 0" in text)
require("scheduler watchdog runs every minute", "setInterval(() => this.watchdogTick('60秒巡检'), 60000)" in text)
require("scheduler watchdog wakes on browser resume", "window.addEventListener('focus'" in text and "document.visibilityState === 'visible'" in text and "window.addEventListener('pageshow'" in text)
require("scheduler watchdog resumes active phase", "恢复 ${phase.id}/${phase.state}" in text and "await Router.run();" in text)
require("scheduler watchdog fires overdue home task", "entry.nextRunAt <= nowMs" in text and "await this.fireToTarget(due);" in text)
require("scheduler allows manual browsing before task is due", "手动浏览 ${path}，无到点任务，不打断" in text and "if (due)" in text)
require("scheduler returns home only for due task", "${due.id} 已到点，从 ${path} 返回首页执行" in text and "await this.navigateHome();" in text)
require("scheduler start does not force home", "启动调度器不打断手动浏览" in text and "this.navigateHome();\n      }" not in text[text.index("    start() {"):text.index("    stop(reason", text.index("    start() {"))])
require("due task keeps original time while returning home", "保留原到点时间" in text and "推后 1min" not in text)
require("scheduler keeps timer alive on manual pages", "任何页面都维持计时，但不主动离开手动浏览页" in text and "if (currentPath === '/xz/')" not in text[text.index("// ---- 无 phase：任何页面"):text.index("// ---- phase=navigating")])
require("enabled scheduler restores watchdog after reload", "if (Scheduler.isOn()) {" in init_block and "Scheduler.startWatchdog();" in init_block)
require("scheduler prevents watchdog timer double fire", "忽略重复触发 ${entry.id}" in text and "const existingPhase = Utils.gget(PHASE_KEY, null);" in text)

print(f"\nAll regression checks passed: {SCRIPT}")
